util = require('util')
exec = require('child_process').exec

# 設定
SOURCE_DIR = './source'
TARGET_DIR = './build'
TARGET_FILENAME = 'build.js'

#コンパイルするファイル群
files = [
    'clirooo.coffee'
    'setting.coffee'
    'util.coffee'
    'subcommand/station.coffee'
    'subcommand/help.coffee'
    'subcommand/mannar.coffee'
    'subcommand/ascii.coffee'
    'subcommand/status.coffee'
    'subcommand/delay.coffee'
    'subcommand/line.coffee'
    'subcommand/timetable.coffee'
    'subcommand/route.coffee'
    'subcommand/here.coffee'
    'subcommand/config.coffee'
    'subcommand/invite.coffee'
    'console.coffee'
    'cmd-handler.coffee'
]

# タスクの登録
task 'build', 'CoffeeScriptをまとめてひとつのJavaScriptにします', (options) ->

    # ファイルを構成する
    util.log('まとめるファイルを構成します')
    fileList = []

    for filename, index in files
        file = SOURCE_DIR + '/' + filename
        fileList.push(file)
        util.log("#{index + 1}) #{file}")

    fileList = fileList.join(' ')
    
    # コンパイル実行
    util.log('コンパイルします')
    exec "cat  #{fileList} | coffee --compile --stdio > #{TARGET_DIR}/#{TARGET_FILENAME}", (error, stdout, stderr) -> 

        util.log(error) if error
        util.log(stdout) if stdout
        util.log(stderr) if stderr

        if error
            util.log('失敗しました')
        else
            util.log('成功しました')